app/posts/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint,send_file
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)
from werkzeug.utils import secure_filename

from app.models import (User, Post, Comment)
from app.forms import (LoginForm, RegistrationForm, PostForm, CommentForm)
import pandas as pd
from datetime import datetime
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import matplotlib.pyplot as plt
import seaborn as sns
import os
import io
import json
import base64

posts = Blueprint('posts', __name__)

fig,ax = plt.subplots(figsize=(6,6))
ax=sns.set_style(style='darkgrid')

# x= [1,2,3]
# y= ["one", "two", "three"]

def current_time() -> str:
    return datetime.now().strftime("%B %d")

def get_b64_imgs_index():
        posts = Post.objects()    
        temp = []
        for post in posts:
            bytes_im = io.BytesIO(post.image.read())    
            image = base64.b64encode(bytes_im.getvalue()).decode()
            temp.append(image)
        return temp

@posts.route('/')
@posts.route('/index')
def index():
    users = User.objects()
    posts = Post.objects()      
    comments = Comment.objects()

    return render_template("index.html", title='Home', users=users, posts=posts, images=get_b64_imgs_index())
    

def get_b64_imgs_profile(username):
        user = User.objects(username=username).first()
        posts = Post.objects(author=user)    
        temp = []
        for post in posts:
            bytes_im = io.BytesIO(post.image.read())    
            image = base64.b64encode(bytes_im.getvalue()).decode()
            temp.append(image)
        return temp

@posts.route("/profile/<username>", methods=["GET", "POST"])
def profile(username):
    # handle the post form
    postform = PostForm()
    if postform.validate_on_submit():
        img = postform.image.data
        filename = secure_filename(img.filename)
        content_type = f'/images/{filename[-3:]}'

        newPost = Post(
            postid=f'post{len(Post.objects())}',
            author=current_user._get_current_object(),
            date=current_time(),
            caption=postform.caption.data
        )
        newPost.image.put(img.stream, content_type=content_type)
        
        newPost.save()

        flash('Successfully Posted')
        return redirect(url_for('posts.profile', username=username))
    
    # get all posts
    user = User.objects(username=username).first()
    posts = Post.objects(author=user)

    # list of lists of comments for posts
    comments = []
    for post in posts:
        comments.append( Comment.objects(postid=post.postid) )

    arr = []
    for i in posts:
        date = i.date
        if [date,0] not in arr:
            arr.append([i.date,0])

    for a in arr:
        for i in posts:
            if a[0] == i.date:
                a[1] += 1
    
    x = json.dumps([row[0] for row in arr])
    y = json.dumps([row[1] for row in arr])
    
    return render_template('profile.html', username=username, postform=postform, posts=posts, images=get_b64_imgs_profile(username), comments=comments,x=x,y=y)


def get_b64_img_post(postid):
    post = Post.objects(postid=postid).first()
    bytes_im = io.BytesIO(post.image.read())    
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image   


@posts.route("/post/<postid>", methods=["GET", "POST"])
def post(postid):
    post = Post.objects(postid=postid).first()
    commentform=CommentForm()
    if commentform.validate_on_submit():
        newComment = Comment(
            postid = postid,
            author = current_user._get_current_object(),
            date = current_time(),
            comment = commentform.comment.data
        )
        newComment.save()

        flash('Successfully Commented')
        return redirect(url_for('posts.post', postid=postid))

    comments = Comment.objects(postid=postid)

    return render_template('post.html', post=post, commentform=commentform, image=get_b64_img_post(postid), comments=comments)

app/users/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)
from werkzeug.utils import secure_filename

from app import bcrypt, mail

from app.models import (User, Post, Comment)
from app.forms import (LoginForm, RegistrationForm, PostForm, CommentForm)

from datetime import datetime

from flask_mail import Message
import plotly
import plotly.graph_objs as go
import os
import io
import json
import base64

users = Blueprint('users', __name__)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if (user is not None and bcrypt.check_password_hash(user.password, form.password.data)):
           login_user(user)
           flash(f'{current_user.username} Successfully Logged In')
           return redirect(url_for('posts.profile', username=current_user.username))
        else:
            flash('Wrong Username or Password')

    return render_template("login.html", title='Login', form=form)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index'))    
    
    form = RegistrationForm()
    if form.validate_on_submit():        
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')        
        user = User(username=form.username.data,email=form.email.data, password=hashed)        
        user.save()
        flash('Successfully Registered')
        return redirect(url_for('users.send_mail', name=form.username.data, email=form.email.data))
    
    return render_template('register.html', title='Register', form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('posts.index'))

@users.route('/send_mail/<name>/<email>')
def send_mail(name, email):
    msg = Message(subject='Thank you for Registering ' + name, body="We really appreciate you signing up " + name + "! Let us know if you have any questions.", sender='ericliam388J@gmail.com', recipients=[email])
    mail.send(msg)
    return redirect(url_for('users.login'))

app/templates/base.html
<html>
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

      {% if username %}
      <title>@{{ username }}</title>
      {% else %}
      <title>User</title>
      {% endif %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </head>
    <body>
        <div>
            <center><h1 class="mt-0">User: {{ current_user.username }}</h1></center>
               

            <nav class="navbar navbar-dark text-primary">
                <div class="container">
                    <a class="navbar-brand" href="{{ url_for('posts.index') }}">Home</a>
                    {% if current_user.is_authenticated %}
                    <a class="navbar-brand" href="{{ url_for('posts.profile', username = current_user.username) }}">Profile</a>
                    <a class="navbar-brand" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                    <a class="navbar-brand" href="{{ url_for('users.login') }}">Login</a>
                    <a class="navbar-brand" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
            
                    <!-- <form class="d-flex">
                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Search</button>
                            </form> -->
            </nav>
        </div>
    </br>

        

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="mx-auto" style="width: 300px;">
    <div class="container">
        <center>
            <h1>Feed</h1>
            {% if current_user.is_authenticated %}
            {% else %} 
                Login to see user profiles
                </br></br>
            {% endif %}
        </center>
    </div>

    <!-- show all posts by user -->
    {% for i in range(posts|length)[::-1] %}
    <div>
        
        <div class="container" style="width: 300px;">
            <div class="row">
                <div class="col">
                    {% if current_user.is_authenticated %} 
                        <h6> &nbsp;<a href="{{ url_for('posts.profile', username = posts[i].author.username) }}">@{{ posts[i].author.username }}</a></h6>
                    {% else %}
                        @{{ posts[i].author.username }}
                    {% endif %}
                </div>
                <div class="col-sm" style="width: 90px">
                    <div align="right">{{ posts[i].date }}</div>
                </div>
            </div>
        </div>
        <div class="container">
            <img class="mr-3 comment-pic" src="data:image/png;base64,{{images[i]}}" alt="" height=300 width=300>
        </div>
        <div class="container-md mt-1">
            Caption: {{ posts[i].caption }}
        </div> 
        <div class="container">
            <center><a href="{{ url_for('posts.post', postid=posts[i].postid ) }}">visit post page</a></center>
        </div>
        </br></br>
        {% endfor %}
        <!-- add few comments and post link here -->

    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    
    <center>
        <h1>Sign In</h1>
        <form method="POST" action="">
            {{ form.csrf_token }}
            <div class="form-group" style="width: 40%;">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
        
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        
        </br>
        
            <div class="form-group mb-2" style="width: 40%;">
                    <label for="exampleInputEmail1" class="form-label">{{ form.password.label }}</label>
                    {{ form.password(class="form-control") }}
        
                    {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <!-- {{ form.submit() }} -->
        </form>
        <div>
            <p> Don't have an account yet?
                <a href="{{ url_for('users.register')}}"> Register Here</a>
            </p>
        </div>
    </center>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block content %}
<div align=center>
    <h1> {{post.author.username}}'s post: </h1>
    <!-- show all posts by user -->
    <div>
        <hr width=400>
        <p> <a href="{{ url_for('posts.profile', username = post.author.username) }}">@{{ post.author.username }}</a>
            <br>
            Timestamp: {{ post.date }} <br>
            Caption: {{ post.caption }}
        </p>
        <img class="mr-3 comment-pic" src="data:image/png;base64,{{image}}" alt="" height=300 width=300>

        {% if current_user.is_authenticated %}
        <form method="POST" action="">
            {{ commentform.csrf_token }}
            <div class="form-group mb-2" style="width: 30%;">
                {{ commentform.comment.label }}
                {{ commentform.comment(class="form-control") }}
                
                {% if commentform.comment.errors %}
                <div class="alert alert-warning" role="alert">
                {% for error in commentform.comment.errors %}
                <span>{{ error }}</span>
                {% endfor %}
                </div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
        {% endif %}


        {% if comments %}
        <h4>Comments:</h4>
        {% for i in range(comments|length) %}
        <p> <a href="{{ url_for('posts.profile', username = comments[i].author.username) }}">@{{ comments[i].author.username }}</a>: {{comments[i].comment}} </p>
        {% endfor %}
        {% endif %}

    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="mx-auto" style="width: 50%;">
    <center><h1> {{username}}'s Page </h1>
    <h5> {{posts|length}} Posts</h5></center>
    <!-- for making posts -->
    {% if current_user.username == username %}
    
    <h2> Make a Post </h2>
    <div>
        <form method=post enctype=multipart/form-data>
            {{ postform.csrf_token }}

            <div class="form-group">
                {{ postform.image.label }}
                {{ postform.image(class="form-control") }}
                {% if postform.image.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in postform.image.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ postform.caption.label }}
                {{ postform.caption(class="form-control") }}
                {% if postform.caption.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in postform.caption.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <br>
            <button type="submit" class="btn btn-primary"> Post </button>
        </form>
    </div>
    <br>
    {% endif %}




    <h5>Insights</h5>

    <div id="chart" class="chart">
    </div>
     <div class="ct-chart ct-perfect-fourth"></div>
                <script>
                    lab = JSON.parse({{ x | tojson }})
                    dat = JSON.parse({{ y | tojson }})
                    var data = {
                        // A labels array that can contain any sort of values
                        labels: lab,
                        // Our series array that contains series objects or in this case series data arrays
                        series: [
                            dat
                        ]
                    };

                    // Create a new line chart object where as first parameter we pass in a selector
                    // that is resolving to our chart container element. The Second parameter
                    // is the actual data object.
                    new Chartist.Bar('.ct-chart', data);
                </script>
    <!-- {{ plt }} -->
    {{ x }}
    {{ y }}
    

    <center><h2>All Posts</h2></br></center>
    <!-- show all posts by user -->
    {% for i in range(posts|length)[::-1] %}
    <!-- <hr width=400> -->
    <center>
        
        <div>
            
                Date: {{ posts[i].date }}</p> 
                <img class="mr-3 comment-pic" src="data:image/png;base64,{{images[i]}}" alt="" height=300 width=300></br>
                Caption: {{ posts[i].caption }} 
            
        
            <!-- add few comments and post link here -->
            <br>
            
            <a href="{{ url_for('posts.post', postid=posts[i].postid ) }}">visit post page</a>
                </br></br>
        </div>
    </center>
    {% endfor %}
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
    <center>
        <h1>Create Account</h1>
        </br>
        <form method="POST" action="">
            {{ form.csrf_token }}
            <div class="form-group" style="width: 40%;">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
        
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        
        </br>

            <div class="form-group" style="width: 40%;">
                {{ form.email.label }}
                {{ form.email(class="form-control") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        
        </br>

            <div class="form-group" style="width: 40%;">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        
        </br>

            <div class="form-group" style="width: 40%;">
                {{ form.confirm_password.label }}
                {{ form.confirm_password(class="form-control") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </br>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
        <div>
            <p> Already have an account?
                <a href="{{ url_for('users.login')}}"> Login Here</a>
            </p>
        </div>
    </center>
    
{% endblock %}